[[edge_functions]]
  path = "/*/*"
  function = "metadata"

[[redirects]]
  from = "/bot/link"
  to = "/.netlify/functions/linkbot"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200